server:
  port: 18889

##spring配置项
spring:
  application:
    name: drewshop-user-service-provider
  datasource:
    url: jdbc:mysql://121.5.137.64:3306/drewshop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: Sunshine123,.

nacos:
  config:
    server-addr: 192.158.158.131:8848

# Dubbo配置项
dubbo:
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: only.undrewyan.drewshop.userservice.rpc
  registry:
    address: nacos://${nacos.config.server-addr}
  application:
    name: ${spring.application.name}
  provider:
    TestRpc:
      version: 1.0.0

# MyBatis Plus 配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 虽然默认为 true ，但是还是显示去指定下。